services:
  npm: &npm
    profiles: [tasks]
    env_file:
      - path: .env
        required: false
    tty: true
    stdin_open: true
    build:
      context: .
      target: builder
    entrypoint: npm
    command: help
    volumes:
      - .:/usr/src/app:delegated
      - node_modules:/node_modules:cached

  npx: &npx
    <<: *npm
    profiles: [tasks]
    entrypoint: npx
    command: -h

  node:
    <<: *npm
    profiles: [tasks]
    entrypoint: node
    command: --help

  # We can't use <<: *npm with develop.watch due to the volume overlap.
  app:
    env_file:
      - path: .env
        required: false
    tty: true
    stdin_open: true
    build:
      context: .
      target: builder
    entrypoint: npm
    command: run start
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    develop:
      watch:
        - action: sync+restart
          path: ./src/
          target: /usr/src/app/src/
        - action: sync+restart
          path: ./package.json
          target: /usr/src/app/package.json
        - action: sync+restart
          path: ./package-lock.json
          target: /usr/src/app/package-lock.json
    volumes:
      - node_modules:/node_modules:cached

  install:
    <<: *npm
    profiles: [tasks]
    command: install --include=dev

  lint:
    <<: *npx
    profiles: [tasks]
    command: eslint
    depends_on:
      - install

  test:
    <<: *npx
    profiles: [tasks]
    command: mocha
    depends_on:
      - install

  person-service:
    image: ghcr.io/gitops-ci-cd/person-service:5321defb239e7c1e0fb8b79f2274b9b754f05a03
    environment:
      - PORT=50051
      - LOG_LEVEL=DEBUG

  greeting-service:
    image: ghcr.io/gitops-ci-cd/greeting-service:d7f87fd4984b2c3c576f5b2b002e8f69afc743f6
    environment:
      - PORT=50051
      - LOG_LEVEL=DEBUG

volumes:
  node_modules: {}
