on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - main

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write
  deployments: write

name: Deployment

jobs:
  production:
    name: Production
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: production

  sandbox:
    needs: production
    name: Sandbox
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: sandbox

  build:
    needs: sandbox
    name: Image
    uses: gitops-ci-cd/.github/.github/workflows/build.yaml@main

  release:
    needs: build
    name: GitHub
    uses: gitops-ci-cd/.github/.github/workflows/release.yaml@main
