on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  deployments: write

name: Integrate

jobs:
  lint:
    if: github.event.action != 'labeled'
    name: Integrate
    uses: gitops-ci-cd/.github/.github/workflows/lint.yaml@main

  test:
    if: github.event.action != 'labeled'
    name: Integrate
    uses: gitops-ci-cd/.github/.github/workflows/test.yaml@main

  deploy_preview:
    needs:
      - lint
      - test
    if: github.event.action == 'labeled' && github.event.label.name == 'preview' || github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'preview')
    name: Preview
    uses: gitops-ci-cd/.github/.github/workflows/deployment.yaml@main
    with:
      environment: preview

  build:
    needs: deploy_preview
    name: Image
    uses: gitops-ci-cd/.github/.github/workflows/build.yaml@main
